### ISSUE TITLE
error validating app spec

### ISSUE THREAD

**Issue by beneberle** [DO-Solutions/DigitalOcean-AppPlatform-Cron#2]
I followed [this tutorial](https://docs.digitalocean.com/developer-center/how-to-setup-a-job-scheduler-on-digitalocean-app-platform/) to try setting up the worker but am not able to update the app spec with the following error:

`Error: PUT https://api.digitalocean.com/v2/apps/xxxxxxxx-xxxxx-xxxxxx: 400 (request "xxxxxxxx-xxxxx-xxxxxx") error validating app spec field "ingress.rules.rule.component.name": ingress rules only support services, functions, and static_sites. seen in component name: "docker-cron" for path: "/docker-cron"

Any advice?

**Comment by jkpe** [comment]
Hi @beneberle 👋 
Thanks for reporting this issue.

Please can you share your full app spec you are trying here for me to review? Feel free to redact anything.

**Comment by beneberle** [comment]
Hi @jkpe It turns out that my attempts at customization of the Dockerfile to my needs were causing the issue, so no issue with the repo at all, just in my knowledge gap. Closing, thanks for the reply.
